from __future__ import annotations

import importlib.util
import io
import json
from pathlib import Path
import subprocess
import sys
import tarfile
import tempfile
import textwrap
import unittest
from contextlib import redirect_stdout


ROOT = Path(__file__).resolve().parents[1]
HARNESS_PATH = ROOT / "scripts" / "codex_meta_harness.py"
PI_DOCKER_PATH = ROOT / "scripts" / "pi_docker_benchmark.py"

spec = importlib.util.spec_from_file_location("codex_meta_harness", HARNESS_PATH)
assert spec is not None
harness = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(harness)

docker_spec = importlib.util.spec_from_file_location("pi_docker_benchmark", PI_DOCKER_PATH)
assert docker_spec is not None
pi_docker = importlib.util.module_from_spec(docker_spec)
assert docker_spec.loader is not None
docker_spec.loader.exec_module(pi_docker)


def git(root: Path, *args: str) -> None:
    proc = subprocess.run(
        [
            "git",
            "-c",
            "user.name=Test User",
            "-c",
            "user.email=test@example.com",
            *args,
        ],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        raise AssertionError(proc.stderr)


def write_fixture_repo(root: Path) -> Path:
    (root / "docs" / "prompt-sets").mkdir(parents=True)
    (root / "scripts").mkdir()
    (root / "docs" / "participant-task.md").write_text(
        "# Task\n\nTarget: `{{TARGET_MILESTONE}}`\n", encoding="utf-8"
    )
    (root / "docs" / "prompt-sets" / "browser-build-v0.md").write_text(
        "# Prompt Set\n", encoding="utf-8"
    )
    (root / "specs.zip").write_bytes(b"fixture specs")
    (root / "scripts" / "vibe_bench.py").write_text(
        textwrap.dedent(
            """\
            import sys

            if sys.argv[1:] == ["validate"]:
                print("fixture validation ok")
                raise SystemExit(0)
            raise SystemExit(2)
            """
        ),
        encoding="utf-8",
    )
    fake_codex = root / "fake_codex.py"
    fake_codex.write_text(
        textwrap.dedent(
            """\
            import json
            import pathlib
            import sys

            argv_log = pathlib.Path(sys.argv[1])
            args = sys.argv[2:]
            argv_log.parent.mkdir(parents=True, exist_ok=True)
            with argv_log.open("a", encoding="utf-8") as handle:
                handle.write(json.dumps(args) + "\\n")

            output = None
            for index, value in enumerate(args):
                if value == "--output-last-message":
                    output = pathlib.Path(args[index + 1])
                    break
            if output is not None:
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_text("fake turn complete\\n", encoding="utf-8")

            pathlib.Path("generated-browser.txt").write_text(
                "generated by fake codex\\n", encoding="utf-8"
            )
            sys.stdin.read()
            print(json.dumps({
                "type": "session.started",
                "session_id": "fake-session",
                "usage": {"total_tokens": 17},
                "tool_call_count": 2,
            }))
            """
        ),
        encoding="utf-8",
    )
    git(root, "init")
    git(root, "config", "user.name", "Test User")
    git(root, "config", "user.email", "test@example.com")
    git(root, "add", "docs", "scripts", "specs.zip", "fake_codex.py")
    git(root, "commit", "-m", "fixture baseline")
    return fake_codex


def write_fake_pi(root: Path) -> Path:
    fake_pi = root / "fake_pi.py"
    fake_pi.write_text(
        textwrap.dedent(
            """\
            import json
            import pathlib
            import sys

            if "--version" in sys.argv:
                print("pi 0.0-test")
                raise SystemExit(0)

            argv_log = pathlib.Path(sys.argv[1])
            args = sys.argv[2:]
            argv_log.parent.mkdir(parents=True, exist_ok=True)
            with argv_log.open("a", encoding="utf-8") as handle:
                handle.write(json.dumps(args) + "\\n")

            pathlib.Path("generated-pi-browser.txt").write_text(
                "generated by fake pi\\n", encoding="utf-8"
            )
            print(json.dumps({
                "type": "message_update",
                "assistantMessageEvent": {
                    "type": "thinking_delta",
                    "delta": "private reasoning should not stream",
                },
            }))
            print(json.dumps({
                "type": "message_update",
                "assistantMessageEvent": {
                    "type": "toolcall_start",
                    "contentIndex": 0,
                },
                "message": {
                    "content": [
                        {
                            "type": "toolCall",
                            "name": "write",
                            "arguments": {"path": "generated-pi-browser.txt"},
                        }
                    ]
                },
            }))
            print(json.dumps({
                "type": "message",
                "session_id": "rpi",
                "totalTokens": 23,
                "toolCalls": 3,
                "content": "fake pi turn complete",
            }))
            """
        ),
        encoding="utf-8",
    )
    return fake_pi


class CodexMetaHarnessTests(unittest.TestCase):
    def test_ollama_codex_alias_command_builds_initial_and_resume_argv(self) -> None:
        config = {
            "codex_command": "ollama-codex --model glm-5.1:cloud",
            "codex_command_mode": "interactive-shell",
            "codex_model_arg": "auto",
            "model": "glm-5.1:cloud",
            "sandbox_mode": "workspace-write",
        }
        initial = harness.build_codex_argv(
            config,
            Path("/repo"),
            turn_number=1,
            output_last_message=Path("/tmp/last.md"),
            session_id=None,
        )
        self.assertEqual(initial[:2], ["zsh", "-ic"])
        self.assertIn("ollama-codex --model glm-5.1:cloud exec", initial[2])
        self.assertIn("--json --cd /repo", initial[2])
        self.assertEqual(initial[2].count("--model"), 1)
        self.assertIn("--sandbox", initial[2])

        resumed = harness.build_codex_argv(
            config,
            Path("/repo"),
            turn_number=2,
            output_last_message=Path("/tmp/last.md"),
            session_id="fake-session",
        )
        self.assertEqual(resumed[:2], ["zsh", "-ic"])
        self.assertIn(
            "ollama-codex --model glm-5.1:cloud exec resume --json",
            resumed[2],
        )
        self.assertNotIn("--cd", resumed[2])
        self.assertNotIn("--sandbox", resumed[2])
        self.assertTrue(resumed[2].endswith("fake-session -"))

    def test_init_records_ollama_codex_alias_command(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_fixture_repo(root)
            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "init",
                    "--target",
                    "m1",
                    "--profile",
                    "smoke-v0",
                    "--model",
                    "glm-5.1:cloud",
                    "--codex-command",
                    "ollama-codex --model glm-5.1:cloud",
                    "--codex-command-mode",
                    "interactive-shell",
                    "--run-id",
                    "rtest",
                    "--turn-limit",
                    "1",
                ]
            )

            config = json.loads(
                (root / ".vibe-bench" / "runs" / "rtest" / "config.json").read_text(
                    encoding="utf-8"
                )
            )
            self.assertEqual(
                config["codex_command"],
                "ollama-codex --model glm-5.1:cloud",
            )
            self.assertEqual(config["codex_command_mode"], "interactive-shell")
            manifest = (root / "benchmark-run.md").read_text(encoding="utf-8")
            self.assertIn(
                "Codex launch command: ollama-codex --model glm-5.1:cloud",
                manifest,
            )

    def test_run_and_resume_use_recorded_session_and_write_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            fake_codex = write_fixture_repo(root)
            argv_log = root / "argv-log.jsonl"
            codex_command = f"{sys.executable} {fake_codex} {argv_log}"

            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "init",
                    "--target",
                    "m1",
                    "--profile",
                    "smoke-v0",
                    "--model",
                    "glm-5.1:cloud",
                    "--codex-command",
                    codex_command,
                    "--run-id",
                    "rtest",
                    "--turn-limit",
                    "2",
                    "--force",
                ]
            )
            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "run",
                    "--run-id",
                    "rtest",
                    "--max-new-turns",
                    "1",
                ]
            )
            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "resume",
                    "--run-id",
                    "rtest",
                ]
            )

            run_dir = root / ".vibe-bench" / "runs" / "rtest"
            state = json.loads((run_dir / "state.json").read_text(encoding="utf-8"))
            self.assertEqual(state["observed_turns"], 2)
            self.assertEqual(state["session_id"], "fake-session")
            self.assertEqual(state["observed_token_usage"], 17)
            self.assertEqual(state["observed_tool_calls"], 2)
            self.assertEqual(state["latest_verification"], "passed")
            self.assertEqual(state["stop_reason"], "budget-exhausted-turn-limit")

            self.assertTrue((run_dir / "prompts" / "turn-0001.md").exists())
            self.assertTrue((run_dir / "prompts" / "turn-0002.md").exists())
            self.assertTrue((run_dir / "codex" / "turn-0001.jsonl").exists())
            self.assertTrue((run_dir / "codex" / "turn-0002.last.md").exists())
            self.assertTrue((run_dir / "verification" / "turn-0002.txt").exists())
            self.assertTrue((run_dir / "checkpoints" / "checkpoint-0002.json").exists())

            argv_lines = [
                json.loads(line)
                for line in argv_log.read_text(encoding="utf-8").splitlines()
            ]
            self.assertIn("exec", argv_lines[0])
            self.assertNotIn("resume", argv_lines[0])
            self.assertIn("resume", argv_lines[1])
            self.assertEqual(argv_lines[1][-2:], ["fake-session", "-"])

            manifest = (root / "benchmark-run.md").read_text(encoding="utf-8")
            self.assertIn("- Observed turns: 2", manifest)
            self.assertIn("- Latest verification result: passed", manifest)
            self.assertIn("- Comparison eligible: yes", manifest)

    def test_checkpoint_commits_can_commit_new_material_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            fake_codex = write_fixture_repo(root)
            argv_log = root / "argv-log.jsonl"
            codex_command = f"{sys.executable} {fake_codex} {argv_log}"
            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "init",
                    "--target",
                    "m1",
                    "--profile",
                    "smoke-v0",
                    "--model",
                    "glm-5.1:cloud",
                    "--codex-command",
                    codex_command,
                    "--run-id",
                    "rtest",
                    "--turn-limit",
                    "1",
                    "--checkpoint-commits",
                ]
            )
            harness.main(["--repo-root", str(root), "run", "--run-id", "rtest"])
            state = json.loads(
                (
                    root / ".vibe-bench" / "runs" / "rtest" / "state.json"
                ).read_text(encoding="utf-8")
            )
            self.assertRegex(state["latest_checkpoint_commit"], r"^[0-9a-f]{40}$")
            proc = subprocess.run(
                ["git", "log", "--oneline", "-n", "1"],
                cwd=root,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
            self.assertIn("checkpoint(rtest): turn 1", proc.stdout)

    def test_pi_adapter_builds_expected_ollama_command(self) -> None:
        config = {
            "agent_kind": "pi",
            "pi_command": "pi",
            "model_provider": "ollama",
            "model": "glm-5.1:cloud",
            "pi_mode": "json",
            "run_id": "rpi",
            "pi_tools": "read,write,edit,bash,grep,find,ls",
        }
        argv = harness.build_pi_argv(
            config,
            Path("/repo"),
            prompt="hello",
            session_dir=Path("/repo/.vibe-bench/runs/rpi/pi/sessions"),
        )
        self.assertEqual(argv[:9], ["pi", "--provider", "ollama", "--model", "glm-5.1:cloud", "--mode", "json", "--print", "--session-id"])
        self.assertIn("--session-dir", argv)
        self.assertIn("--tools", argv)
        self.assertEqual(argv[-1], "hello")

    def test_pi_init_and_run_write_pi_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_fixture_repo(root)
            fake_pi = write_fake_pi(root)
            argv_log = root / "pi-argv-log.jsonl"
            pi_command = f"{sys.executable} {fake_pi} {argv_log}"

            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "init",
                    "--agent-kind",
                    "pi",
                    "--target",
                    "m1",
                    "--profile",
                    "smoke-v0",
                    "--wall-clock-limit",
                    "10m",
                    "--model-provider",
                    "ollama",
                    "--model",
                    "glm-5.1:cloud",
                    "--pi-command",
                    pi_command,
                    "--container-execution",
                    "docker-admin-v0",
                    "--run-id",
                    "rpi",
                    "--turn-limit",
                    "1",
                ]
            )
            harness.main(["--repo-root", str(root), "run", "--run-id", "rpi"])

            run_dir = root / ".vibe-bench" / "runs" / "rpi"
            state = json.loads((run_dir / "state.json").read_text(encoding="utf-8"))
            self.assertEqual(state["observed_turns"], 1)
            self.assertEqual(state["session_id"], "rpi")
            self.assertEqual(state["observed_token_usage"], 23)
            self.assertEqual(state["observed_tool_calls"], 3)
            self.assertEqual(state["latest_verification"], "passed")
            self.assertEqual(state["stop_reason"], "budget-exhausted-turn-limit")
            self.assertTrue((run_dir / "pi" / "turn-0001.jsonl").exists())
            self.assertTrue((run_dir / "pi" / "turn-0001.last.md").exists())
            self.assertTrue((run_dir / "pi" / "sessions").exists())
            models_json = json.loads(
                (run_dir / "pi" / "agent" / "models.json").read_text(
                    encoding="utf-8"
                )
            )
            ollama_provider = models_json["providers"]["ollama"]
            self.assertEqual(
                ollama_provider["baseUrl"], "http://host.docker.internal:11434/v1"
            )
            self.assertEqual(ollama_provider["api"], "openai-completions")
            self.assertEqual(ollama_provider["apiKey"], "ollama")
            self.assertEqual(
                ollama_provider["models"],
                [{"id": "glm-5.1:cloud"}],
            )

            argv_lines = [
                json.loads(line)
                for line in argv_log.read_text(encoding="utf-8").splitlines()
            ]
            self.assertIn("--provider", argv_lines[0])
            self.assertIn("ollama", argv_lines[0])
            self.assertIn("--model", argv_lines[0])
            self.assertIn("glm-5.1:cloud", argv_lines[0])
            self.assertIn("--session-id", argv_lines[0])
            self.assertIn("rpi", argv_lines[0])

            manifest = (root / "benchmark-run.md").read_text(encoding="utf-8")
            self.assertIn("- Agent kind: pi", manifest)
            self.assertIn("- Provider interface: pi-cli-v0", manifest)
            self.assertIn("- Model provider: ollama", manifest)
            self.assertIn("- PI command:", manifest)

    def test_stream_agent_events_prints_compact_progress(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_fixture_repo(root)
            fake_pi = write_fake_pi(root)
            argv_log = root / "pi-argv-log.jsonl"
            pi_command = f"{sys.executable} {fake_pi} {argv_log}"

            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "init",
                    "--agent-kind",
                    "pi",
                    "--target",
                    "m1",
                    "--profile",
                    "smoke-v0",
                    "--model-provider",
                    "ollama",
                    "--model",
                    "glm-5.1:cloud",
                    "--pi-command",
                    pi_command,
                    "--run-id",
                    "rpi",
                    "--turn-limit",
                    "1",
                ]
            )

            output = io.StringIO()
            with redirect_stdout(output):
                harness.main(
                    [
                        "--repo-root",
                        str(root),
                        "run",
                        "--run-id",
                        "rpi",
                        "--stream-agent-events",
                    ]
                )
            live = output.getvalue()
            self.assertIn("[rpi turn 1] starting pi", live)
            self.assertIn("[rpi turn 1] tool write", live)
            self.assertIn("[rpi turn 1] exited code=0", live)
            self.assertNotIn("private reasoning should not stream", live)

    def test_live_agent_summary_filters_thinking_and_shows_tools(self) -> None:
        config = {"run_id": "rpi", "tool_name": "pi"}
        thinking = json.dumps(
            {
                "type": "message_update",
                "assistantMessageEvent": {
                    "type": "thinking_delta",
                    "delta": "private reasoning",
                },
            }
        )
        tool = json.dumps(
            {
                "type": "message_update",
                "assistantMessageEvent": {
                    "type": "toolcall_start",
                    "contentIndex": 0,
                },
                "message": {
                    "content": [
                        {
                            "type": "toolCall",
                            "name": "read",
                            "arguments": {"path": "README.md"},
                        }
                    ]
                },
            }
        )
        finished = json.dumps(
            {
                "type": "message_end",
                "message": {
                    "role": "assistant",
                    "stopReason": "toolUse",
                    "usage": {"totalTokens": 42},
                },
            }
        )

        self.assertIsNone(harness.summarize_agent_event_line(config, 1, thinking))
        self.assertEqual(
            harness.summarize_agent_event_line(config, 1, tool),
            '[rpi turn 1] tool read {"path": "README.md"}',
        )
        self.assertEqual(
            harness.summarize_agent_event_line(config, 1, finished),
            "[rpi turn 1] assistant finished (stop=toolUse, tokens=42)",
        )

    def test_pi_docker_command_uses_disposable_admin_container_without_forbidden_mounts(self) -> None:
        parser = pi_docker.build_parser()
        args = parser.parse_args(
            [
                "run",
                "--skip-build",
                "--run-id",
                "rpi",
                "--target",
                "m1",
                "--wall-clock-limit",
                "10m",
                "--provider",
                "ollama",
                "--model",
                "glm-5.1:cloud",
            ]
        )
        artifacts = Path(tempfile.gettempdir()) / "vibe-browser-pi-artifacts"
        argv = pi_docker.build_docker_run_argv(
            ROOT,
            args,
            run_id="rpi",
        )
        joined = " ".join(argv)
        self.assertIn("--user root", joined)
        self.assertNotIn("--rm", argv)
        self.assertNotIn(":/artifacts", joined)
        self.assertNotIn("/var/run/docker.sock", joined)
        self.assertNotIn(str(Path.home()), joined)
        self.assertIn("--agent-kind pi", joined)
        self.assertIn("--wall-clock-limit 10m", joined)
        self.assertIn("--model-provider ollama", joined)
        self.assertIn("--model glm-5.1:cloud", joined)
        self.assertIn("--stream-agent-events", joined)
        pi_docker.assert_no_forbidden_mounts(argv)
        cp_argv = pi_docker.build_docker_cp_argv("rpi", artifacts)
        self.assertEqual(cp_argv[0:2], ["docker", "cp"])
        self.assertIn(".vibe-bench/docker-export/rpi", cp_argv[2])
        self.assertIn("git-status.txt", joined)
        self.assertIn("untracked-files.tar", joined)

    def test_pi_docker_archives_untracked_files(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            (root / "generated").mkdir()
            (root / "generated" / "browser.py").write_text(
                "print('browser')\n", encoding="utf-8"
            )
            list_file = root / "untracked.zlist"
            list_file.write_bytes(b"generated/browser.py\0missing.txt\0")
            output = root / "untracked.tar"
            parser = pi_docker.build_parser()
            args = parser.parse_args(
                [
                    "--repo-root",
                    str(root),
                    "archive-untracked",
                    "--list-file",
                    str(list_file),
                    "--output",
                    str(output),
                ]
            )

            pi_docker.command_archive_untracked(args)

            with tarfile.open(output) as archive:
                self.assertEqual(archive.getnames(), ["generated/browser.py"])

    def test_verification_handles_markdown_commands_and_missing_executables(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_fixture_repo(root)
            run_dir = root / ".vibe-bench" / "runs" / "rtest"
            run_dir.mkdir(parents=True)
            (root / "benchmark-run.md").write_text(
                textwrap.dedent(
                    """\
                    # Benchmark Run

                    ## Verification

                    - Build command: (none - pure Python, no build step)
                    - Test command: `PYTHONPATH=src python3 -c "import os; assert os.environ['PYTHONPATH'] == 'src'"`
                    - Smoke-test command: `definitely-missing-vibe-browser-command`
                    """
                ),
                encoding="utf-8",
            )

            result, log_path = harness.run_verification(root, "rtest", 1)
            log = log_path.read_text(encoding="utf-8")
            self.assertEqual(result, "failed exit=127")
            self.assertIn("skipped (build)", log)
            self.assertIn("$ PYTHONPATH=src python3", log)
            self.assertIn("definitely-missing-vibe-browser-command", log)
            self.assertIn("FileNotFoundError", log)

    def test_status_and_finalize_update_manifest(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_fixture_repo(root)
            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "init",
                    "--target",
                    "m1",
                    "--profile",
                    "smoke-v0",
                    "--model",
                    "glm-5.1:cloud",
                    "--codex-command",
                    "ollama-codex --model glm-5.1:cloud",
                    "--codex-command-mode",
                    "interactive-shell",
                    "--run-id",
                    "rtest",
                ]
            )

            output = io.StringIO()
            with redirect_stdout(output):
                harness.main(["--repo-root", str(root), "status", "--run-id", "rtest"])
            state = json.loads(output.getvalue())
            self.assertEqual(state["state"], "created")

            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "finalize",
                    "--run-id",
                    "rtest",
                    "--stop-reason",
                    "evaluator-stop",
                    "--comparison-eligible",
                    "no: pilot",
                ]
            )
            manifest = (root / "benchmark-run.md").read_text(encoding="utf-8")
            self.assertIn("- Stop reason: evaluator-stop", manifest)
            self.assertIn("- Comparison eligible: no: pilot", manifest)

            harness.main(
                [
                    "--repo-root",
                    str(root),
                    "log-intervention",
                    "--run-id",
                    "rtest",
                    "--actor",
                    "tester",
                    "--action",
                    "restart controller",
                    "--reason",
                    "exercise audit log",
                ]
            )
            intervention_log = (
                root / ".vibe-bench" / "runs" / "rtest" / "interventions.jsonl"
            )
            entries = [
                json.loads(line)
                for line in intervention_log.read_text(encoding="utf-8").splitlines()
            ]
            self.assertEqual(entries[0]["actor"], "tester")
            self.assertFalse(entries[0]["model_visible_guidance_changed"])

    def test_dangerous_codex_bypass_requires_explicit_opt_in(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            write_fixture_repo(root)
            with self.assertRaises(SystemExit):
                harness.main(
                    [
                        "--repo-root",
                        str(root),
                        "init",
                        "--target",
                        "m1",
                        "--profile",
                        "smoke-v0",
                        "--model",
                        "glm-5.1:cloud",
                        "--codex-command",
                        "codex --dangerously-bypass-approvals-and-sandbox",
                        "--run-id",
                        "rtest",
                    ]
                )


if __name__ == "__main__":
    unittest.main()
